# -*- coding: utf-8 -*-
"""Pyrenderer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1feRmi098NWJQVlyNUBvn2lBR6rnsXJ10
"""

!pip install pyrender trimesh


import trimesh
import pyrender
import numpy as np
import matplotlib.pyplot as plt

# Load the 3D model
apple_mesh = trimesh.load('apple.obj')

# Convert to pyrender mesh
apple_mesh_pyrender = pyrender.Mesh.from_trimesh(apple_mesh)

# Create a scene and add the mesh
scene = pyrender.Scene()
scene.add(apple_mesh_pyrender)

# Set up the camera
camera = pyrender.PerspectiveCamera(yfov=np.pi / 3.0)
camera_pose = np.array([
    [1.0, 0.0,  0.0, 0.0],
    [0.0, 1.0,  0.0, 0.0],
    [0.0, 0.0, 1.0, 4.0],
    [0.0, 0.0, 0.0, 1.0],
])
scene.add(camera, pose=camera_pose)

# Set up the light
light = pyrender.DirectionalLight(color=[1.0, 1.0, 1.0], intensity=2.0)
scene.add(light, pose=camera_pose)

# Render the scene
renderer = pyrender.OffscreenRenderer(640, 480)
color, depth = renderer.render(scene)

# Show the resulting image
plt.figure()
plt.imshow(color)
plt.show()

